# Generated by Django 6.0.5 on 2026-05-25 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notice',
            old_name='content',
            new_name='description',
        ),
    ]
