# Generated by Django 6.0.5 on 2026-05-24 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0003_file_created_at_folder_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='folder',
            name='created_at',
        ),
    ]
