# Generated by Django 6.0.5 on 2026-05-25 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0005_file_created_at_folder_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='description',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
